language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - APP_KEY=i1KLWiqXo12PbsUFqJSb9TId85b8qHU4


matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer install --dev --prefer-source --no-interaction

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-text
