language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - APP_KEY=i1KLWiqXo12PbsUFqJSb9TId85b8qHU4
    - ENVOYER_HOOK=https://envoyer.io/deploy/TbHfKdbEtcC4xljSqOmwU3hZQ4NRvV0bPzPPRthm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer install --dev --prefer-source --no-interaction

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-text

after_success:
  - if [ $TRAVIS_PHP_VERSION = "5.6" ]; then curl $ENVOYER_HOOK; fi
